const TYPE_FACTS = {
  A318:["The Airbus A318 is the smallest member of the original A320 family."],
  A319:["The Airbus A319 is a shortened member of the A320 family and is widely used on short and medium-haul routes."],
  A320:["The Airbus A320 family helped make fly-by-wire flight controls standard in modern single-aisle airliners."],
  A20N:["The A320neo is the newer-generation A320, designed around more efficient engines and aerodynamic improvements."],
  A321:["The Airbus A321 is the longest member of the original A320 family and can carry more passengers than the A320."],
  A21N:["The A321neo combines the larger A321 fuselage with newer-generation engines and improved efficiency."],
  A332:["The Airbus A330-200 is a long-range wide-body aircraft used for both passenger and cargo flying."],
  A333:["The Airbus A330-300 is a twin-engine wide-body commonly used on medium and long-haul routes."],
  A339:["The A330-900 is part of the A330neo family, combining the A330 airframe with newer engines and updated aerodynamics."],
  A359:["The Airbus A350-900 is a long-range wide-body built extensively from lightweight composite materials."],
  A35K:["The Airbus A350-1000 is the largest member of the A350 family and is designed for long-haul flying."],
  A388:["The Airbus A380 is the world's largest passenger airliner and has two full-length passenger decks."],
  B737:["The Boeing 737 family is one of the most widely used families of passenger jets in the world."],
  B738:["The Boeing 737-800 became one of the most common versions of the 737 Next Generation family."],
  B739:["The Boeing 737-900 is the longest member of the 737 Next Generation family."],
  B38M:["The Boeing 737 MAX 8 is a newer-generation 737 designed around more efficient engines and aerodynamic changes."],
  B39M:["The Boeing 737 MAX 9 is the stretched version of the MAX 8, offering additional passenger capacity."],
  B744:["The Boeing 747-400 is one of the best-known versions of the classic four-engine 747 jumbo jet."],
  B748:["The Boeing 747-8 is the final and largest production version of the 747 family."],
  B752:["The Boeing 757-200 is known for strong takeoff performance and has served both short and long sectors."],
  B763:["The Boeing 767-300 is a twin-engine wide-body that has been widely used for passenger flights and air cargo."],
  B772:["The Boeing 777-200 is part of the first generation of Boeing's large twin-engine 777 family."],
  B77L:["The Boeing 777-200LR is a very long-range member of the 777 family and is also the basis for the 777 Freighter."],
  B77W:["The Boeing 777-300ER became one of the most successful long-haul wide-body aircraft of its generation."],
  B788:["The Boeing 787-8 was the first version of the Dreamliner family and makes extensive use of composite materials."],
  B789:["The Boeing 787-9 is the middle-sized Dreamliner and is widely used on long-haul routes."],
  B78X:["The Boeing 787-10 is the longest Dreamliner variant and has the highest passenger capacity in the family."],
  E170:["The Embraer E170 is a regional jet designed for shorter routes and smaller passenger markets."],
  E175:["The Embraer E175 is a popular regional jet, especially on feeder routes into major airline hubs."],
  E75L:["The Embraer E175 is a popular regional jet, especially on feeder routes into major airline hubs."],
  E190:["The Embraer E190 bridges the gap between traditional regional jets and larger single-aisle airliners."],
  E195:["The Embraer E195 is the largest member of the original E-Jet family."],
  CRJ9:["The Bombardier CRJ900 is a stretched regional jet designed to carry more passengers than earlier CRJ variants."],
  AT72:["The ATR 72 is a twin-turboprop regional airliner optimized for relatively short routes."],
  DH8D:["The Dash 8 Q400 is a fast turboprop regional aircraft designed for short and medium-distance services."]
};

module.exports = { TYPE_FACTS };
