function applyOverlayV11(html){
  html=html.replaceAll("Overlay v0.8","Overlay v1.1").replaceAll("Overlay v0.9","Overlay v1.1").replaceAll("Overlay v1.0","Overlay v1.1");
  html=html.replace("</style>",".next-box{display:none!important}.lower-third{right:4vw}.story-text{height:148px;overflow:hidden;position:relative;-webkit-mask-image:linear-gradient(to bottom,transparent 0,#000 9%,#000 88%,transparent 100%);mask-image:linear-gradient(to bottom,transparent 0,#000 9%,#000 88%,transparent 100%)}.story-scroll{will-change:transform;padding:8px 0 18px}.story-scroll p{margin:0 0 15px 0}.story-scroll p:last-child{margin-bottom:8px}</style>");
  html=html.replace("let busy=false,lastCurrentKey=null,radarCurrentKey=null,radarAircraft=[],radarAirport=null,radarSweepAngle=0;","let busy=false,lastCurrentKey=null,radarCurrentKey=null,radarAircraft=[],radarAirport=null,radarSweepAngle=0,lastStoryKey=null,storyScrollFrame=null;");

  const storyStart=html.indexOf("function showStory(data){"),storyEnd=html.indexOf("\nfunction radarRelativeKm",storyStart);
  if(storyStart>=0&&storyEnd>storyStart){
    const newStory=`function startStoryScroll(viewport,scroll){
 if(storyScrollFrame)cancelAnimationFrame(storyScrollFrame);scroll.style.transform="translateY(0px)";const maxScroll=Math.max(0,scroll.scrollHeight-viewport.clientHeight+10);if(maxScroll<=2){storyScrollFrame=null;return}const leadMs=2600,holdMs=5000,speedPxPerMs=.0105;let cycleStart=performance.now();function step(now){const elapsed=now-cycleStart;let y=0;if(elapsed>leadMs)y=Math.min(maxScroll,(elapsed-leadMs)*speedPxPerMs);scroll.style.transform="translateY("+(-y)+"px)";const finishAt=leadMs+(maxScroll/speedPxPerMs)+holdMs;if(elapsed>=finishAt){cycleStart=now;scroll.style.transform="translateY(0px)"}storyScrollFrame=requestAnimationFrame(step)}storyScrollFrame=requestAnimationFrame(step)}
function showStory(data){
 const card=document.getElementById("storyCard"),output=data?.output,story=output?.story,segments=Array.isArray(output?.segments)?output.segments:[];if(!data?.ok||!output?.available||!story){card.classList.remove("visible","verified");lastStoryKey=null;if(storyScrollFrame){cancelAnimationFrame(storyScrollFrame);storyScrollFrame=null}return}
 const verified=story.specificAircraft===true||String(output.class||"").startsWith("VERIFIED_");card.classList.toggle("verified",verified);setText("storyKicker",verified?"AIRCRAFT STORY":"LIVE AIRPORT STORY");setText("storyHeadline",story.headline||"Live airport activity");setText("storyMeta",(verified?"VERIFIED":"SAFE CONTEXT")+" • "+String(output.confidence||0)+"% CONFIDENCE");
 const regFact=Array.isArray(output.facts)?output.facts.find(f=>f?.label==="registration"):null,storyKey=(regFact?.value||story.headline||output.class||"")+"|"+String(story.specificAircraft===true);if(storyKey!==lastStoryKey){lastStoryKey=storyKey;const viewport=document.getElementById("storyText");viewport.innerHTML="";const scroll=document.createElement("div");scroll.className="story-scroll";const items=segments.length?segments.map(s=>s?.text).filter(Boolean):[story.text].filter(Boolean);for(const text of items){const p=document.createElement("p");p.textContent=text;scroll.appendChild(p)}viewport.appendChild(scroll);requestAnimationFrame(()=>startStoryScroll(viewport,scroll))}card.classList.add("visible")
}`;
    html=html.slice(0,storyStart)+newStory+html.slice(storyEnd);
  }

  const radarStart=html.indexOf("function drawRadar(){"),radarEnd=html.indexOf("\nasync function update(){",radarStart);
  if(radarStart>=0&&radarEnd>radarStart){
    const newRadar=`function drawRadar(){
 const canvas=document.getElementById("radarCanvas"),wrap=canvas.parentElement,dpr=window.devicePixelRatio||1,w=wrap.clientWidth,h=wrap.clientHeight,pw=Math.round(w*dpr),ph=Math.round(h*dpr);if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w,h)*.46;
 ctx.strokeStyle="rgba(83,226,185,.23)";ctx.lineWidth=1;[.25,.5,.75,1].forEach(q=>{ctx.beginPath();ctx.arc(cx,cy,r*q,0,Math.PI*2);ctx.stroke()});ctx.strokeStyle="rgba(83,226,185,.16)";ctx.beginPath();ctx.moveTo(cx-r,cy);ctx.lineTo(cx+r,cy);ctx.moveTo(cx,cy-r);ctx.lineTo(cx,cy+r);ctx.stroke();ctx.fillStyle="rgba(141,235,208,.55)";ctx.font="700 "+Math.max(9,w*.035)+"px Arial";ctx.textAlign="center";ctx.fillText("N",cx,cy-r+13);ctx.fillText("S",cx,cy+r-8);ctx.fillText("W",cx-r+12,cy+4);ctx.fillText("E",cx+r-12,cy+4);
 const sr=radarSweepAngle*Math.PI/180,g=ctx.createConicGradient(sr,cx,cy);g.addColorStop(0,"rgba(73,255,190,.30)");g.addColorStop(.07,"rgba(73,255,190,.10)");g.addColorStop(.18,"rgba(73,255,190,0)");g.addColorStop(1,"rgba(73,255,190,0)");ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(104,255,205,.7)";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.sin(sr)*r,cy-Math.cos(sr)*r);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(cx,cy,3,0,Math.PI*2);ctx.fill();
 if(radarAirport&&Array.isArray(radarAircraft)){for(const a of radarAircraft){const lat=Number(a.lat),lon=Number(a.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const rel=radarRelativeKm(lat,lon,radarAirport.lat,radarAirport.lon),dist=Math.hypot(rel.eastKm,rel.northKm);if(dist>RADAR_RANGE_KM)continue;const x=cx+(rel.eastKm/RADAR_RANGE_KM)*r,y=cy-(rel.northKm/RADAR_RANGE_KM)*r,isCurrent=radarKey(a)===radarCurrentKey,targetAngle=Math.atan2(rel.eastKm,rel.northKm),sweepDiff=Math.abs(Math.atan2(Math.sin(sr-targetAngle),Math.cos(sr-targetAngle))),sweepGlow=Math.max(0,1-sweepDiff/.22);if(sweepGlow>0){ctx.save();ctx.shadowColor=isCurrent?"rgba(255,202,87,.9)":"rgba(104,255,194,.9)";ctx.shadowBlur=10+18*sweepGlow;ctx.fillStyle=isCurrent?"rgba(255,202,87,"+(.05+.18*sweepGlow)+")":"rgba(104,255,194,"+(.04+.16*sweepGlow)+")";ctx.beginPath();ctx.arc(x,y,(isCurrent?7:4)+7*sweepGlow,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.fillStyle=isCurrent?"#ffca57":a.onGround?"#6dc6ff":"#68ffc2";ctx.beginPath();ctx.arc(x,y,isCurrent?5.5:2.6,0,Math.PI*2);ctx.fill();if(isCurrent){ctx.strokeStyle="rgba(255,202,87,.82)";ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(x,y,9.5,0,Math.PI*2);ctx.stroke();const label=document.getElementById("flight")?.textContent||a.callsign||a.registration||"";ctx.save();ctx.font="800 "+Math.max(12,w*.043)+"px Arial";ctx.textAlign="left";ctx.textBaseline="middle";ctx.lineJoin="round";ctx.miterLimit=2;ctx.lineWidth=Math.max(3,w*.012);ctx.strokeStyle="rgba(0,10,15,.92)";ctx.shadowColor="rgba(0,0,0,.85)";ctx.shadowBlur=5;ctx.strokeText(label,x+12,y);ctx.fillStyle="#fff1b8";ctx.shadowColor="rgba(255,202,87,.28)";ctx.shadowBlur=4;ctx.fillText(label,x+12,y);ctx.restore()}}}radarSweepAngle=(radarSweepAngle+.75)%360;requestAnimationFrame(drawRadar)
}`;
    html=html.slice(0,radarStart)+newRadar+html.slice(radarEnd);
  }

  const updateStart=html.indexOf("async function update(){"),updateEnd=html.indexOf("\ndrawRadar();",updateStart);
  if(updateStart>=0&&updateEnd>updateStart){
    const newUpdate=`async function update(){
 if(busy)return;busy=true;const p=new URLSearchParams(window.location.search),airport=(p.get("airport")||"PRG").trim().toUpperCase();try{const br=await fetch("/api/broadcast?airport="+encodeURIComponent(airport)+"&t="+Date.now(),{cache:"no-store"}),bt=await br.text(),data=JSON.parse(bt);if(!br.ok||!data.ok)throw new Error(data.error||"Broadcast API failed");const current=data.aircraft?.current;if(current?.available&&current.route?.found){const ids={PRG:["PRG","LKPR"],LHR:["LHR","EGLL"],FRA:["FRA","EDDF"],AMS:["AMS","EHAM"],CDG:["CDG","LFPG"],MAN:["MAN","EGCC"],ATL:["ATL","KATL"]},local=ids[airport]||[airport],endpointMatches=e=>{if(!e)return false;const a=String(e.iata||"").toUpperCase(),b=String(e.icao||"").toUpperCase();return local.includes(a)||local.includes(b)},lineage=String(current.movement?.lineage||"").toUpperCase(),routeOK=lineage==="ARRIVAL"?endpointMatches(current.route.destination):lineage==="DEPARTURE"?endpointMatches(current.route.origin):false;if(!routeOK)current.route={...current.route,found:false,display:null,map:null,suppressed:true,suppressedReason:"Route not coherent with CURRENT movement"}}
 const storyParams=new URLSearchParams({airport:airport,t:String(Date.now())});if(current?.available){if(current.identity?.registration)storyParams.set("registration",current.identity.registration);if(current.identity?.callsign)storyParams.set("callsign",current.identity.callsign)}else{storyParams.set("registration","__NO_CURRENT__")}
 const [er,sr]=await Promise.all([fetch("/api/engine?airport="+encodeURIComponent(airport)+"&t="+Date.now(),{cache:"no-store"}),fetch("/api/storyteller?"+storyParams.toString(),{cache:"no-store"})]),[et,st]=await Promise.all([er.text(),sr.text()]),engine=JSON.parse(et),story=JSON.parse(st);showMain(current);showNext(null);if(sr.ok&&story.ok)showStory(story);else showStory(null);if(er.ok&&engine.ok){radarAircraft=Array.isArray(engine.aircraft)?engine.aircraft:[];radarAirport={lat:Number(engine.airport?.lat),lon:Number(engine.airport?.lon)};if(!Number.isFinite(radarAirport.lat)||!Number.isFinite(radarAirport.lon))radarAirport=null}}catch(e){console.error("Overlay update failed:",e)}finally{busy=false}}
`;
    html=html.slice(0,updateStart)+newUpdate+html.slice(updateEnd);
  }
  return html;
}
module.exports={applyOverlayV11};
