function applyOverlayV13(html,pinnedAirport){
  html=html.replaceAll("Overlay v1.2","Overlay v1.3");
  html=html.replace(`const p=new URLSearchParams(window.location.search),airport=(p.get("airport")||"PRG").trim().toUpperCase();`,`const airport=${JSON.stringify(pinnedAirport)};`);
  html=html.replace("</style>",`.story-card{display:none!important}\n.story-ticker{height:40px;display:none;align-items:center;overflow:hidden;position:relative;background:rgba(5,22,38,.985);border-left:1px solid rgba(100,197,255,.34);border-right:1px solid rgba(100,197,255,.34);border-top:1px solid rgba(100,197,255,.18);color:#dcecf5;box-shadow:inset 0 1px 0 rgba(255,255,255,.03)}\n.story-ticker.visible{display:flex}.story-ticker.verified{border-top-color:rgba(255,202,87,.45)}\n.story-ticker-label{position:absolute;left:0;top:0;bottom:0;z-index:2;display:flex;align-items:center;padding:0 13px;background:linear-gradient(90deg,rgba(4,29,49,1),rgba(4,29,49,.96));color:#79dfff;font-size:10px;font-weight:900;letter-spacing:1.1px;white-space:nowrap;border-right:1px solid rgba(105,205,255,.25)}\n.story-ticker.verified .story-ticker-label{color:#ffd77d;border-right-color:rgba(255,202,87,.3)}\n.story-ticker-viewport{position:absolute;left:92px;right:0;top:0;bottom:0;overflow:hidden;display:flex;align-items:center}\n.story-ticker-track{position:absolute;left:0;white-space:nowrap;font-size:clamp(12px,.92vw,16px);font-weight:650;letter-spacing:.1px;color:#e8f4fa;will-change:transform}\n.telemetry-strip{border-radius:0 0 12px 12px!important}\n.main-ribbon{border-radius:12px 12px 0 0!important}\n</style>`);
  html=html.replace(`<div class="telemetry-strip">`,`<div id="storyTicker" class="story-ticker"><div id="storyTickerLabel" class="story-ticker-label">AIRCRAFT STORY</div><div id="storyTickerViewport" class="story-ticker-viewport"><div id="storyTickerTrack" class="story-ticker-track"></div></div></div><div class="telemetry-strip">`);
  html=html.replace("lastStoryKey=null,storyScrollFrame=null,lastRouteKey=null;","lastStoryKey=null,storyScrollFrame=null,lastRouteKey=null,lastGoodStoryAt=0,lastGoodStoryAircraftKey=null,lastCoherentMapAircraftKey=null,lastCoherentMapRoute=null,radarTopLabel=null;");
  html=html.replace(`if(isCurrent){ctx.strokeStyle="rgba(255,202,87,.82)";ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(x,y,9.5,0,Math.PI*2);ctx.stroke();const label=document.getElementById("flight")?.textContent||a.callsign||a.registration||"";ctx.save();ctx.font="800 "+Math.max(12,w*.043)+"px Arial";ctx.textAlign="left";ctx.textBaseline="middle";ctx.lineJoin="round";ctx.miterLimit=2;ctx.lineWidth=Math.max(3,w*.012);ctx.strokeStyle="rgba(0,10,15,.92)";ctx.shadowColor="rgba(0,0,0,.85)";ctx.shadowBlur=5;ctx.strokeText(label,x+12,y);ctx.fillStyle="#fff1b8";ctx.shadowColor="rgba(255,202,87,.28)";ctx.shadowBlur=4;ctx.fillText(label,x+12,y);ctx.restore()}`,
    `if(isCurrent){ctx.strokeStyle="rgba(255,202,87,.82)";ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(x,y,9.5,0,Math.PI*2);ctx.stroke();const label=document.getElementById("flight")?.textContent||a.callsign||a.registration||"";radarTopLabel={x,y,label};}else if(dist>=6&&(a.callsign||a.registration)){const label=String(a.callsign||a.registration||"").trim();if(label){ctx.save();ctx.font="700 "+Math.max(8,w*.028)+"px Arial";ctx.textBaseline="middle";ctx.textAlign=x>cx?"right":"left";const offset=x>cx?-7:7;ctx.lineJoin="round";ctx.lineWidth=2.5;ctx.strokeStyle="rgba(0,12,16,.88)";ctx.strokeText(label,x+offset,y);ctx.fillStyle="rgba(194,255,232,.88)";ctx.fillText(label,x+offset,y);ctx.restore()}}`);
  html=html.replace(` }}\n radarSweepAngle=(radarSweepAngle+.75)%360;requestAnimationFrame(drawRadar)`,` }}\n if(radarTopLabel&&radarTopLabel.label){const {x,y,label}=radarTopLabel;ctx.save();ctx.font="800 "+Math.max(12,w*.043)+"px Arial";ctx.textAlign="left";ctx.textBaseline="middle";ctx.lineJoin="round";ctx.miterLimit=2;ctx.lineWidth=Math.max(3,w*.012);ctx.strokeStyle="rgba(0,10,15,.96)";ctx.shadowColor="rgba(0,0,0,.9)";ctx.shadowBlur=6;ctx.strokeText(label,x+12,y);ctx.fillStyle="#fff1b8";ctx.shadowColor="rgba(255,202,87,.35)";ctx.shadowBlur=5;ctx.fillText(label,x+12,y);ctx.restore()}radarTopLabel=null;\n radarSweepAngle=(radarSweepAngle+.75)%360;requestAnimationFrame(drawRadar)`);

  const storyStart=html.indexOf("function showStory(data){"),storyEnd=html.indexOf("\nfunction radarRelativeKm",storyStart);
  if(storyStart>=0&&storyEnd>storyStart){
    const storyRenderer=`function hideStoryTicker(){
 const ticker=document.getElementById("storyTicker");if(ticker)ticker.classList.remove("visible","verified");if(storyScrollFrame){cancelAnimationFrame(storyScrollFrame);storyScrollFrame=null}}
function startStoryTicker(text,key,verified,labelText){
 const ticker=document.getElementById("storyTicker"),viewport=document.getElementById("storyTickerViewport"),track=document.getElementById("storyTickerTrack"),label=document.getElementById("storyTickerLabel");
 if(!ticker||!viewport||!track)return;if(key===lastStoryKey&&ticker.classList.contains("visible"))return;lastStoryKey=key;if(storyScrollFrame){cancelAnimationFrame(storyScrollFrame);storyScrollFrame=null}
 ticker.classList.toggle("verified",Boolean(verified));if(label)label.textContent=labelText||"AIRCRAFT STORY";track.textContent=text||"";track.style.transform="translateX(0px)";ticker.classList.add("visible");
 requestAnimationFrame(()=>{const width=viewport.clientWidth,textWidth=track.scrollWidth,speed=.032,leadMs=1400,tailMs=1800;let cycleStart=performance.now();function step(now){const elapsed=now-cycleStart,travel=width+textWidth;let x=width;if(elapsed>leadMs)x=width-Math.min(travel,(elapsed-leadMs)*speed);track.style.transform="translateX("+x+"px)";const finishAt=leadMs+(travel/speed)+tailMs;if(elapsed>=finishAt){cycleStart=now;track.style.transform="translateX("+width+"px)"}storyScrollFrame=requestAnimationFrame(step)}storyScrollFrame=requestAnimationFrame(step)});}
function showStory(data){const output=data?.output,story=output?.story,segments=Array.isArray(output?.segments)?output.segments:[];if(!data?.ok||!output?.available||!story)return;const verified=story.specificAircraft===true||String(output.class||"").startsWith("VERIFIED_");const regFact=Array.isArray(output.facts)?output.facts.find(f=>f?.label==="registration"):null;const storyKey=(regFact?.value||story.headline||output.class||"")+"|"+String(story.specificAircraft===true);const items=segments.length?segments.map(s=>s?.text).filter(Boolean):[story.text].filter(Boolean);const headline=story.headline?story.headline+" — ":"";startStoryTicker(headline+items.join("   •   "),storyKey,verified,verified?"AIRCRAFT STORY":"LIVE STORY");}`;
    html=html.slice(0,storyStart)+storyRenderer+html.slice(storyEnd);
  }

  const updateAt=html.indexOf("async function update(){");
  if(updateAt>=0){
    const helpers=`function showSafeLiveContext(current,airportInfo){if(!current?.available){hideStoryTicker();return}const safeKey="SAFE|"+(identityKey(current)||"");const state=current.movement?.displayState||current.movement?.state||"Aircraft in view",airportName=airportInfo?.name||airportInfo?.code||"the airport",runway=current.movement?.runway,distance=Number(current.telemetry?.airportDistanceKm),parts=[state+" at "+airportName+"."];if(runway)parts.push("Runway "+runway+".");if(Number.isFinite(distance))parts.push("About "+distance.toFixed(1)+" kilometres from the airport reference point.");parts.push("More details will appear when they can be verified.");startStoryTicker(parts.join("   •   "),safeKey,false,"LIVE CONTEXT");}
function showStableRouteMap(current){const currentKey=identityKey(current)||"";if(current?.route?.found){lastCoherentMapAircraftKey=currentKey;lastCoherentMapRoute=current.route;showRouteMap(current);return}if(currentKey&&currentKey===lastCoherentMapAircraftKey&&lastCoherentMapRoute?.found){showRouteMap({...current,route:lastCoherentMapRoute});return}lastCoherentMapAircraftKey=currentKey||null;lastCoherentMapRoute=null;document.getElementById("routeMapCard").classList.remove("visible");routeAnimationActive=false;}
`;
    html=html.slice(0,updateAt)+helpers+html.slice(updateAt);
  }
  html=html.replace(` map.classList.remove("visible");story.classList.remove("visible","verified");`,` map.classList.remove("visible");story.classList.remove("visible","verified");hideStoryTicker();`);
  html=html.replace(`  if(current?.available&&!closing){\n   const storyCard=document.getElementById("storyCard");\n   if(current.route?.found){storyCard.classList.remove("mapless");showRouteMap(current)}\n   else{document.getElementById("routeMapCard").classList.remove("visible");routeAnimationActive=false;storyCard.classList.add("mapless")}\n  }else if(!current?.available||closing){\n   hideInfoPanel();\n  }`,`  if(current?.available&&!closing){\n   showStableRouteMap(current);\n  }else if(!current?.available||closing){\n   lastCoherentMapAircraftKey=null;\n   lastCoherentMapRoute=null;\n   hideInfoPanel();\n  }`);
  const oldBlock=`  if(current?.available&&!closing){
   if(!current.route?.found)showLocalMovementMap(current,engine,airport);
   if(srOK&&story?.ok)showStory(story);else document.getElementById("storyCard").classList.remove("visible","verified")
  }

  if(engine?.ok){`;
  const newBlock=`  if(current?.available&&!closing){
   const currentStoryKey=identityKey(current)||"";
   const storyUsable=Boolean(srOK&&story?.ok&&story?.output?.available);
   if(storyUsable){showStory(story);lastGoodStoryAt=Date.now();lastGoodStoryAircraftKey=currentStoryKey;}else{const sameAircraft=currentStoryKey&&currentStoryKey===lastGoodStoryAircraftKey;const tickerVisible=document.getElementById("storyTicker")?.classList.contains("visible");if(!(sameAircraft&&tickerVisible&&(Date.now()-lastGoodStoryAt)<20000))showSafeLiveContext(current,data.airport);}
  }

  if(engine?.ok){`;
  if(html.includes(oldBlock))html=html.replace(oldBlock,newBlock);
  return html;
}
module.exports={applyOverlayV13};
