// MikeAircraft Livestream Overlay
// Version 0.7
//
// Broadcast graphics:
// - CURRENT lower third
// - NEXT aircraft
// - genuine live radar
// - auto-zoom geographic route map with land/coast outlines

module.exports = async function handler(req, res) {
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MikeAircraft Overlay v0.7</title>
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:Arial,Helvetica,sans-serif}body{background:#202020}.overlay{position:relative;width:100vw;height:100vh}
.dev-badge{position:absolute;top:18px;left:50%;transform:translateX(-50%);z-index:20;padding:7px 11px;border-radius:7px;background:rgba(0,0,0,.55);color:#9ed8f5;font-size:12px;font-weight:700}
.route-map-card{position:absolute;top:3.5vh;left:3vw;width:clamp(310px,26vw,500px);height:clamp(190px,16vw,305px);overflow:hidden;border-radius:15px;border:1px solid rgba(98,197,255,.48);background:linear-gradient(145deg,rgba(4,21,38,.98),rgba(7,45,70,.96));box-shadow:0 14px 36px rgba(0,0,0,.38),inset 0 0 35px rgba(71,184,237,.05);opacity:0;transform:translateY(-20px) scale(.97);transition:opacity .5s ease,transform .5s ease;pointer-events:none}
.route-map-card.visible{opacity:1;transform:translateY(0) scale(1)}#routeCanvas{position:absolute;inset:0;width:100%;height:100%}.route-map-title{position:absolute;top:12px;left:16px;z-index:4;color:#9edcf7;font-size:clamp(9px,.7vw,12px);font-weight:800;letter-spacing:1.4px}.route-map-route{position:absolute;top:30px;left:16px;z-index:4;color:white;font-size:clamp(20px,1.8vw,31px);font-weight:800;text-shadow:0 2px 10px rgba(0,0,0,.75)}.route-map-cities{position:absolute;bottom:11px;left:16px;right:16px;z-index:4;color:#b7d0df;font-size:clamp(9px,.75vw,12px);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:0 1px 4px rgba(0,0,0,.8)}
.radar-wrap{position:absolute;top:3.5vh;right:3vw;width:clamp(230px,18vw,355px);aspect-ratio:1/1;border-radius:50%;background:radial-gradient(circle,rgba(4,30,37,.88) 0%,rgba(2,18,25,.94) 72%,rgba(1,10,16,.97) 100%);border:2px solid rgba(79,229,188,.62);box-shadow:0 0 28px rgba(49,221,174,.17),inset 0 0 28px rgba(49,221,174,.08);overflow:hidden}#radarCanvas{position:absolute;inset:0;width:100%;height:100%}.radar-title{position:absolute;top:10px;left:50%;transform:translateX(-50%);color:rgba(169,255,226,.92);font-size:clamp(9px,.65vw,12px);font-weight:800;letter-spacing:1.4px;z-index:4}.radar-range{position:absolute;bottom:10px;left:50%;transform:translateX(-50%);color:rgba(139,220,197,.72);font-size:clamp(8px,.55vw,10px);letter-spacing:.8px;z-index:4}
.lower-third{position:absolute;left:4vw;right:28vw;bottom:5vh;opacity:0;transform:translateY(28px);transition:opacity .4s ease,transform .4s ease}.lower-third.visible{opacity:1;transform:translateY(0)}.main-ribbon{position:relative;display:grid;grid-template-columns:minmax(0,1.7fr) minmax(220px,.8fr);min-height:145px;overflow:hidden;border-radius:12px 12px 0 0;background:linear-gradient(105deg,rgba(4,28,53,.98),rgba(0,83,138,.97),rgba(5,30,53,.98));border:1px solid rgba(100,197,255,.42);box-shadow:0 15px 35px rgba(0,0,0,.38)}.main-ribbon:before{content:"";position:absolute;left:0;top:0;bottom:0;width:7px;background:linear-gradient(#5ee2ff,#2388c3)}.identity{position:relative;padding:20px 26px 18px 30px}.airline{color:#c4e4f6;font-size:clamp(16px,1.25vw,22px);font-weight:700;margin-bottom:4px}.flight-row{display:flex;align-items:baseline;flex-wrap:wrap;gap:14px}.flight{color:#fff;font-size:clamp(34px,3vw,52px);font-weight:800;line-height:1;letter-spacing:-1px}.route{color:#61dcff;font-size:clamp(22px,2vw,33px);font-weight:800}.aircraft-line{margin-top:12px;font-size:clamp(15px,1.15vw,20px);color:#fff;font-weight:700}.registration{color:#bed2df;margin-left:10px;font-weight:500}.status-panel{padding:20px 24px 18px 18px;display:flex;flex-direction:column;align-items:flex-end;justify-content:center;text-align:right}.status{display:inline-block;padding:7px 13px;border-radius:18px;color:#6cf0ad;background:rgba(69,227,154,.13);border:1px solid rgba(97,236,171,.48);font-size:clamp(13px,1vw,17px);font-weight:800;margin-bottom:11px}.runway-text{color:#d3e9f6;font-size:clamp(13px,1vw,17px)}
.telemetry-strip{display:grid;grid-template-columns:repeat(4,1fr);min-height:52px;background:rgba(6,18,31,.97);border:1px solid rgba(100,197,255,.25);border-top:none;border-radius:0 0 12px 12px;overflow:hidden}.metric{display:flex;justify-content:center;align-items:center;gap:8px;border-right:1px solid rgba(255,255,255,.09);padding:10px 8px}.metric:last-child{border-right:none}.metric-label{color:#7f9db2;font-size:clamp(10px,.75vw,12px);text-transform:uppercase}.metric-value{color:#fff;font-size:clamp(13px,1vw,17px);font-weight:800}
.next-box{position:absolute;right:4vw;bottom:5vh;width:21vw;min-width:290px;max-width:430px;opacity:0;transform:translateY(24px);transition:opacity .4s ease,transform .4s ease}.next-box.visible{opacity:1;transform:translateY(0)}.next-header{padding:9px 13px;border-radius:10px 10px 0 0;background:rgba(5,18,31,.97);border:1px solid rgba(100,197,255,.26);border-bottom:none;color:#9dcfe9;font-size:12px;font-weight:800}.next-body{padding:13px 15px 15px;border-radius:0 0 10px 10px;background:linear-gradient(110deg,rgba(12,29,45,.97),rgba(18,53,78,.97));border:1px solid rgba(100,197,255,.28)}.next-flight{color:#ffbd59;font-size:clamp(22px,1.8vw,30px);font-weight:800}.next-airline{color:#d3e1ea;font-size:clamp(12px,.95vw,15px);font-weight:700}.next-route{color:#75dfff;font-size:clamp(14px,1.1vw,18px);font-weight:800;margin-top:5px}.next-aircraft{color:#aebfcb;font-size:clamp(11px,.85vw,14px);margin-top:7px}
@media(max-width:900px){.route-map-card{width:300px;height:190px}.radar-wrap{width:210px}.lower-third{left:3vw;right:3vw;bottom:20vh}.main-ribbon{grid-template-columns:1fr}.status-panel{align-items:flex-start;text-align:left}.telemetry-strip{grid-template-columns:repeat(2,1fr)}.next-box{left:3vw;right:3vw;bottom:3vh;width:auto;max-width:none}}
</style>
</head>
<body>
<div class="overlay">
<div class="dev-badge">MikeAircraft Overlay v0.7</div>
<div id="routeMapCard" class="route-map-card"><canvas id="routeCanvas"></canvas><div class="route-map-title">FLIGHT ROUTE</div><div id="routeMapRoute" class="route-map-route">---</div><div id="routeMapCities" class="route-map-cities">---</div></div>
<div class="radar-wrap"><canvas id="radarCanvas"></canvas><div class="radar-title">LIVE RADAR</div><div class="radar-range">20 KM</div></div>
<div id="lowerThird" class="lower-third"><div class="main-ribbon"><div class="identity"><div id="airline" class="airline">---</div><div class="flight-row"><div id="flight" class="flight">---</div><div id="route" class="route">---</div></div><div class="aircraft-line"><span id="aircraft">---</span><span id="registration" class="registration"></span></div></div><div class="status-panel"><div id="status" class="status">---</div><div id="runwayText" class="runway-text">---</div></div></div><div class="telemetry-strip"><div class="metric"><span class="metric-label">Distance</span><span id="distance" class="metric-value">---</span></div><div class="metric"><span class="metric-label">Altitude</span><span id="altitude" class="metric-value">---</span></div><div class="metric"><span class="metric-label">Speed</span><span id="speed" class="metric-value">---</span></div><div class="metric"><span class="metric-label">Runway</span><span id="runway" class="metric-value">---</span></div></div></div>
<div id="nextBox" class="next-box"><div class="next-header">NEXT</div><div class="next-body"><div id="nextFlight" class="next-flight">---</div><div id="nextAirline" class="next-airline">---</div><div id="nextRoute" class="next-route">---</div><div id="nextAircraft" class="next-aircraft">---</div></div></div>
</div>
<script>
const UPDATE_INTERVAL=5000;
const RADAR_RANGE_KM=20;
const ROUTE_ANIMATION_MS=5200;
let busy=false,lastCurrentKey=null,radarCurrentKey=null,radarAircraft=[],radarAirport=null,radarSweepAngle=0;
let routeTimer=null,routeAnimationStart=0,routeAnimationActive=false,routeData=null;
function setText(id,value){const e=document.getElementById(id);if(e)e.textContent=value}
function identityKey(t){return t?.identity?.registration||t?.identity?.callsign||null}

const WORLD_LAND=[
 [[-168,72],[-145,70],[-130,58],[-125,50],[-123,40],[-117,32],[-106,23],[-97,18],[-88,18],[-82,25],[-80,31],[-75,40],[-65,47],[-60,55],[-72,62],[-95,72],[-125,74],[-150,73]],
 [[-82,12],[-75,8],[-70,-5],[-66,-15],[-62,-25],[-57,-35],[-52,-50],[-66,-55],[-74,-45],[-78,-30],[-80,-10]],
 [[-11,36],[-10,43],[-5,49],[2,52],[8,58],[17,60],[24,66],[32,70],[42,70],[40,61],[30,55],[27,45],[19,40],[10,36],[2,36]],
 [[-17,36],[-5,35],[10,37],[24,32],[34,30],[43,12],[51,11],[48,-10],[40,-20],[32,-34],[18,-35],[10,-31],[2,-25],[-5,-5],[-14,14]],
 [[27,36],[38,42],[47,49],[58,55],[70,58],[82,55],[92,52],[106,53],[120,48],[133,42],[145,47],[160,58],[178,63],[178,45],[162,38],[145,34],[130,29],[122,20],[110,18],[102,8],[92,10],[84,22],[75,28],[63,25],[52,30],[42,34]],
 [[112,-11],[124,-14],[135,-19],[146,-29],[153,-38],[145,-44],[132,-42],[118,-34],[113,-23]],
 [[-52,60],[-35,67],[-25,77],[-42,83],[-60,80],[-72,70]],
 [[43,-13],[50,-15],[50,-25],[44,-26],[42,-19]],
 [[166,-34],[178,-38],[176,-47],[168,-46]]
];
function normalizeLonNear(lon,ref){let x=Number(lon);while(x-ref>180)x-=360;while(x-ref<-180)x+=360;return x}
function getRouteBounds(start,end){const aLat=Number(start.lat),bLat=Number(end.lat),aLon=Number(start.lon);const bLon=normalizeLonNear(Number(end.lon),aLon);let minLat=Math.min(aLat,bLat),maxLat=Math.max(aLat,bLat),minLon=Math.min(aLon,bLon),maxLon=Math.max(aLon,bLon);let latSpan=Math.max(maxLat-minLat,3.5),lonSpan=Math.max(maxLon-minLon,5);const latMid=(minLat+maxLat)/2,lonMid=(minLon+maxLon)/2;const targetAspect=1.65;const correctedLon=Math.max(lonSpan,latSpan*targetAspect);const correctedLat=Math.max(latSpan,lonSpan/targetAspect);return{minLat:latMid-correctedLat*.72,maxLat:latMid+correctedLat*.72,minLon:lonMid-correctedLon*.68,maxLon:lonMid+correctedLon*.68,centerLon:lonMid}}
function mapProjection(lat,lon,w,h,b){const left=w*.055,right=w*.945,top=h*.24,bottom=h*.86;const xLon=normalizeLonNear(Number(lon),b.centerLon);return{x:left+((xLon-b.minLon)/(b.maxLon-b.minLon))*(right-left),y:top+((b.maxLat-Number(lat))/(b.maxLat-b.minLat))*(bottom-top)}}
function drawWorld(ctx,w,h,b){
 const sea=ctx.createLinearGradient(0,0,0,h);sea.addColorStop(0,"rgba(5,38,61,.98)");sea.addColorStop(1,"rgba(2,22,37,.98)");ctx.fillStyle=sea;ctx.fillRect(0,0,w,h);
 ctx.strokeStyle="rgba(97,185,216,.09)";ctx.lineWidth=1;
 const lonStep=(b.maxLon-b.minLon)>100?30:(b.maxLon-b.minLon)>35?10:5;const latStep=(b.maxLat-b.minLat)>60?20:(b.maxLat-b.minLat)>25?10:5;
 for(let lon=Math.floor(b.minLon/lonStep)*lonStep;lon<=b.maxLon;lon+=lonStep){const p1=mapProjection(b.minLat,lon,w,h,b),p2=mapProjection(b.maxLat,lon,w,h,b);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}
 for(let lat=Math.floor(b.minLat/latStep)*latStep;lat<=b.maxLat;lat+=latStep){const p1=mapProjection(lat,b.minLon,w,h,b),p2=mapProjection(lat,b.maxLon,w,h,b);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}
 for(const poly of WORLD_LAND){ctx.beginPath();let started=false;for(const point of poly){const p=mapProjection(point[1],point[0],w,h,b);if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y)}ctx.closePath();ctx.fillStyle="rgba(31,91,91,.62)";ctx.fill();ctx.strokeStyle="rgba(104,211,203,.42)";ctx.lineWidth=1.2;ctx.stroke()}
 const vignette=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.15,w/2,h/2,Math.max(w,h)*.65);vignette.addColorStop(0,"rgba(0,0,0,0)");vignette.addColorStop(1,"rgba(0,0,0,.28)");ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h)
}
function showRouteMap(t){if(!t?.route?.found||!t.route.map)return;const start=t.route.map.start,end=t.route.map.end;if(start?.lat==null||start?.lon==null||end?.lat==null||end?.lon==null)return;routeData={start,end,originCode:t.route.origin?.iata||t.route.origin?.icao||"",destinationCode:t.route.destination?.iata||t.route.destination?.icao||""};setText("routeMapRoute",t.route.display||"");const o=t.route.origin?.city||t.route.origin?.name||"",d=t.route.destination?.city||t.route.destination?.name||"";setText("routeMapCities",o+"  →  "+d);const card=document.getElementById("routeMapCard");card.classList.add("visible");routeAnimationStart=performance.now();routeAnimationActive=true;clearTimeout(routeTimer);routeTimer=setTimeout(()=>{card.classList.remove("visible");routeAnimationActive=false},ROUTE_ANIMATION_MS)}
function drawRouteMap(){const canvas=document.getElementById("routeCanvas"),card=canvas.parentElement,dpr=window.devicePixelRatio||1,w=card.clientWidth,h=card.clientHeight,pw=Math.round(w*dpr),ph=Math.round(h*dpr);if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!routeData){requestAnimationFrame(drawRouteMap);return}const b=getRouteBounds(routeData.start,routeData.end);drawWorld(ctx,w,h,b);const s=mapProjection(routeData.start.lat,routeData.start.lon,w,h,b),e=mapProjection(routeData.end.lat,routeData.end.lon,w,h,b);const dx=e.x-s.x,dy=e.y-s.y,len=Math.hypot(dx,dy),mx=(s.x+e.x)/2,my=(s.y+e.y)/2,nx=len?(-dy/len):0,ny=len?(dx/len):-1,bend=Math.min(90,Math.max(34,len*.24)),cx=mx+nx*bend,cy=my+ny*bend;
 ctx.save();ctx.shadowColor="rgba(96,221,255,.75)";ctx.shadowBlur=9;ctx.strokeStyle="rgba(103,225,255,.24)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.quadraticCurveTo(cx,cy,e.x,e.y);ctx.stroke();ctx.restore();
 let progress=routeAnimationActive?Math.min(1,(performance.now()-routeAnimationStart)/ROUTE_ANIMATION_MS):1;const steps=100,visible=Math.floor(steps*progress);ctx.save();ctx.shadowColor="rgba(88,226,255,.95)";ctx.shadowBlur=8;ctx.strokeStyle="rgba(110,232,255,.98)";ctx.lineWidth=3;ctx.beginPath();let markerX=s.x,markerY=s.y;for(let i=0;i<=visible;i++){const t=i/steps,u=1-t,x=u*u*s.x+2*u*t*cx+t*t*e.x,y=u*u*s.y+2*u*t*cy+t*t*e.y;markerX=x;markerY=y;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();ctx.restore();
 const font="bold "+Math.max(10,w*.031)+"px Arial";ctx.font=font;ctx.textBaseline="middle";
 ctx.save();ctx.shadowColor="rgba(94,226,255,.8)";ctx.shadowBlur=9;ctx.fillStyle="#5ee2ff";ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle="#d8f6ff";ctx.textAlign=s.x>w*.72?"right":"left";ctx.fillText(routeData.originCode,s.x+(ctx.textAlign==="left"?9:-9),s.y-10);
 ctx.save();ctx.shadowColor="rgba(255,255,255,.7)";ctx.shadowBlur=10;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(e.x,e.y,6,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle="#fff";ctx.textAlign=e.x<w*.28?"left":"right";ctx.fillText(routeData.destinationCode,e.x+(ctx.textAlign==="left"?9:-9),e.y-10);
 if(progress<1){ctx.save();ctx.shadowColor="rgba(255,202,87,.95)";ctx.shadowBlur=12;ctx.fillStyle="#ffca57";ctx.beginPath();ctx.arc(markerX,markerY,5,0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle="rgba(255,202,87,.45)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(markerX,markerY,10,0,Math.PI*2);ctx.stroke()}
 requestAnimationFrame(drawRouteMap)}

function showMain(t){const box=document.getElementById("lowerThird");if(!t||!t.available){box.classList.remove("visible");radarCurrentKey=null;return}setText("airline",t.operator?.name||"Operator not identified");setText("flight",t.identity?.flight||t.identity?.callsign||"---");setText("route",t.route?.display||"");setText("aircraft",t.aircraft?.name||t.aircraft?.typeCode||"---");setText("registration",t.identity?.registration?"• "+t.identity.registration:"");setText("status",t.movement?.displayState||t.movement?.state||"---");setText("runwayText",t.movement?.runway?"RUNWAY "+t.movement.runway:"");setText("distance",t.telemetry?.airportDistanceKm!=null?t.telemetry.airportDistanceKm+" km":"---");setText("altitude",t.telemetry?.altitudeFt!=null?t.telemetry.altitudeFt+" ft":"---");setText("speed",t.telemetry?.speedKt!=null?t.telemetry.speedKt+" kt":"---");setText("runway",t.movement?.runway||"---");box.classList.add("visible");const key=identityKey(t);radarCurrentKey=key;if(key&&key!==lastCurrentKey){lastCurrentKey=key;if(t.route?.found)showRouteMap(t)}}
function chooseNext(data){const c=data.aircraft?.current,ni=data.aircraft?.nextIn,no=data.aircraft?.nextOut;if(c?.available){if(c.movement?.lineage==="ARRIVAL")return ni?.available?ni:no?.available?no:null;if(c.movement?.lineage==="DEPARTURE")return no?.available?no:ni?.available?ni:null}return ni?.available?ni:no?.available?no:null}
function showNext(t){const box=document.getElementById("nextBox");if(!t||!t.available){box.classList.remove("visible");return}setText("nextFlight",t.identity?.flight||t.identity?.callsign||"---");setText("nextAirline",t.operator?.name||"Operator not identified");setText("nextRoute",t.route?.display||"");setText("nextAircraft",(t.aircraft?.name||t.aircraft?.typeCode||"---")+(t.identity?.registration?" • "+t.identity.registration:""));box.classList.add("visible")}
function radarRelativeKm(lat,lon,centerLat,centerLon){return{northKm:(lat-centerLat)*111.32,eastKm:(lon-centerLon)*111.32*Math.cos(centerLat*Math.PI/180)}}
function radarKey(a){return a.registration||a.callsign||a.id||a.hex||null}
function drawRadar(){const canvas=document.getElementById("radarCanvas"),wrap=canvas.parentElement,dpr=window.devicePixelRatio||1,w=wrap.clientWidth,h=wrap.clientHeight,pw=Math.round(w*dpr),ph=Math.round(h*dpr);if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w,h)*.46;ctx.strokeStyle="rgba(83,226,185,.23)";ctx.lineWidth=1;[.25,.5,.75,1].forEach(q=>{ctx.beginPath();ctx.arc(cx,cy,r*q,0,Math.PI*2);ctx.stroke()});ctx.strokeStyle="rgba(83,226,185,.16)";ctx.beginPath();ctx.moveTo(cx-r,cy);ctx.lineTo(cx+r,cy);ctx.moveTo(cx,cy-r);ctx.lineTo(cx,cy+r);ctx.stroke();ctx.fillStyle="rgba(141,235,208,.55)";ctx.font="700 "+Math.max(9,w*.035)+"px Arial";ctx.textAlign="center";ctx.fillText("N",cx,cy-r+13);ctx.fillText("S",cx,cy+r-8);ctx.fillText("W",cx-r+12,cy+4);ctx.fillText("E",cx+r-12,cy+4);const sr=radarSweepAngle*Math.PI/180,g=ctx.createConicGradient(sr,cx,cy);g.addColorStop(0,"rgba(73,255,190,.30)");g.addColorStop(.07,"rgba(73,255,190,.10)");g.addColorStop(.18,"rgba(73,255,190,0)");g.addColorStop(1,"rgba(73,255,190,0)");ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(104,255,205,.7)";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.sin(sr)*r,cy-Math.cos(sr)*r);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(cx,cy,3,0,Math.PI*2);ctx.fill();if(radarAirport&&Array.isArray(radarAircraft)){for(const a of radarAircraft){const lat=Number(a.lat),lon=Number(a.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const rel=radarRelativeKm(lat,lon,radarAirport.lat,radarAirport.lon),dist=Math.hypot(rel.eastKm,rel.northKm);if(dist>RADAR_RANGE_KM)continue;const x=cx+(rel.eastKm/RADAR_RANGE_KM)*r,y=cy-(rel.northKm/RADAR_RANGE_KM)*r,isCurrent=radarKey(a)===radarCurrentKey;ctx.fillStyle=isCurrent?"#ffca57":a.onGround?"#6dc6ff":"#68ffc2";ctx.beginPath();ctx.arc(x,y,isCurrent?5.5:2.6,0,Math.PI*2);ctx.fill();if(isCurrent){ctx.strokeStyle="rgba(255,202,87,.82)";ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(x,y,9.5,0,Math.PI*2);ctx.stroke();const label=document.getElementById("flight")?.textContent||a.callsign||a.registration||"";ctx.save();ctx.font="800 "+Math.max(12,w*.043)+"px Arial";ctx.textAlign="left";ctx.textBaseline="middle";ctx.lineJoin="round";ctx.miterLimit=2;ctx.lineWidth=Math.max(3,w*.012);ctx.strokeStyle="rgba(0,10,15,.92)";ctx.shadowColor="rgba(0,0,0,.85)";ctx.shadowBlur=5;ctx.strokeText(label,x+12,y);ctx.fillStyle="#fff1b8";ctx.shadowColor="rgba(255,202,87,.28)";ctx.shadowBlur=4;ctx.fillText(label,x+12,y);ctx.restore()}}}radarSweepAngle=(radarSweepAngle+.75)%360;requestAnimationFrame(drawRadar)}
async function update(){if(busy)return;busy=true;const p=new URLSearchParams(window.location.search),airport=(p.get("airport")||"PRG").trim().toUpperCase();try{const [br,er]=await Promise.all([fetch("/api/broadcast?airport="+encodeURIComponent(airport)+"&t="+Date.now(),{cache:"no-store"}),fetch("/api/engine?airport="+encodeURIComponent(airport)+"&t="+Date.now(),{cache:"no-store"})]);const [bt,et]=await Promise.all([br.text(),er.text()]),data=JSON.parse(bt),engine=JSON.parse(et);if(!br.ok||!data.ok)throw new Error(data.error||"Broadcast API failed");showMain(data.aircraft?.current);showNext(chooseNext(data));if(er.ok&&engine.ok){radarAircraft=Array.isArray(engine.aircraft)?engine.aircraft:[];radarAirport={lat:Number(engine.airport?.lat),lon:Number(engine.airport?.lon)};if(!Number.isFinite(radarAirport.lat)||!Number.isFinite(radarAirport.lon))radarAirport=null}}catch(e){console.error("Overlay update failed:",e)}finally{busy=false}}
drawRadar();drawRouteMap();update();setInterval(update,UPDATE_INTERVAL);
</script>
</body>
</html>`;
  return res.status(200).send(html);
};