module.exports = async function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  const html = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MikeAircraft Photo Library</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#07131f;color:#eaf6ff;font-family:Arial,Helvetica,sans-serif}.wrap{max-width:1180px;margin:0 auto;padding:28px}.head{display:flex;align-items:center;gap:16px;margin-bottom:22px}.mark{width:62px;height:62px;border-radius:18px;background:linear-gradient(145deg,#113d5d,#071d2e);display:grid;place-items:center;font-size:32px;box-shadow:0 8px 24px #0008}.title h1{margin:0;font-size:30px}.title p{margin:6px 0 0;color:#9db7c9}.card{background:#0b2031;border:1px solid #25506a;border-radius:16px;padding:20px;margin:16px 0;box-shadow:0 12px 32px #0005}.drop{border:2px dashed #3e7da0;border-radius:14px;padding:30px;text-align:center;background:#0a1927}.drop strong{font-size:20px}.drop p{color:#9db7c9}.btn{appearance:none;border:0;border-radius:10px;padding:12px 18px;font-weight:800;cursor:pointer;background:#2da6df;color:#04131e;margin:5px}.btn.secondary{background:#23455a;color:#d9effb}.btn:disabled{opacity:.4;cursor:not-allowed}input[type=file]{display:none}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.stat{background:#071925;border-radius:12px;padding:14px;text-align:center}.stat b{display:block;font-size:24px;color:#62d5ff}.stat span{font-size:12px;color:#8aa7ba}.progress{height:10px;background:#07131f;border-radius:999px;overflow:hidden;margin:15px 0}.bar{height:100%;width:0;background:linear-gradient(90deg,#37b9f4,#4be3a3);transition:width .2s}.status{color:#b9d2df;min-height:22px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}.thumb{background:#071925;border:1px solid #1d4055;border-radius:12px;overflow:hidden}.thumb img{display:block;width:100%;aspect-ratio:3/2;object-fit:cover}.thumb .meta{padding:9px;font-size:11px;color:#9eb8c8}.good{color:#54e49f}.warn{color:#ffd866}.note{font-size:13px;color:#8facbd;line-height:1.5}.privacy{border-left:4px solid #4be3a3;padding-left:12px}.airport{background:#071925;color:#fff;border:1px solid #315c74;border-radius:8px;padding:9px 12px;font-weight:700}
@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.wrap{padding:14px}}
</style></head><body><div class="wrap">
<div class="head"><div class="mark">✈</div><div class="title"><h1>MikeAircraft Photo Library</h1><p>External-drive importer • burst cleaner • public watermark</p></div></div>
<div class="card privacy"><b>Your originals stay on your drive.</b><div class="note">MikeAircraft analyses the selected files in your browser, chooses the strongest frames from rapid-fire bursts, creates a resized watermarked derivative, and uploads only that derivative.</div></div>
<div class="card"><div class="drop"><strong>Connect your external drive, then choose the whole photo folder</strong><p>JPEG, PNG and WebP. Rapid-fire sequences will be grouped automatically.</p><label class="btn" for="folder">Choose photo folder</label><input id="folder" type="file" webkitdirectory directory multiple accept="image/jpeg,image/png,image/webp"><select id="airport" class="airport"><option value="PRG">Prague (PRG)</option><option value="LHR">Heathrow (LHR)</option><option value="ATL">Atlanta (ATL)</option></select><button id="analyse" class="btn secondary" disabled>Analyse folder</button><button id="uploadBtn" class="btn" disabled>Upload selected photos</button></div>
<div class="stats"><div class="stat"><b id="found">0</b><span>photos found</span></div><div class="stat"><b id="bursts">0</b><span>bursts/groups</span></div><div class="stat"><b id="selected">0</b><span>chosen photos</span></div><div class="stat"><b id="saved">0</b><span>duplicates/burst frames skipped</span></div></div><div class="progress"><div id="bar" class="bar"></div></div><div id="status" class="status">Choose a folder to begin.</div></div>
<div class="card"><h3 style="margin-top:0">Selected preview</h3><div id="preview" class="grid"></div><div class="note" style="margin-top:12px">Preview is limited to the first 30 selected photographs. The importer can process a much larger folder.</div></div>
</div>
<script type="module">
import { upload } from 'https://esm.sh/@vercel/blob@2.6.1/client';
const folder=document.getElementById('folder'),analyse=document.getElementById('analyse'),uploadBtn=document.getElementById('uploadBtn'),statusEl=document.getElementById('status'),bar=document.getElementById('bar'),preview=document.getElementById('preview');
let files=[],chosen=[];
function setStatus(t){statusEl.textContent=t}function setBar(n,d){bar.style.width=(d?Math.round(n/d*100):0)+'%'}
folder.addEventListener('change',()=>{files=[...folder.files].filter(f=>/^image\/(jpeg|png|webp)$/i.test(f.type));document.getElementById('found').textContent=files.length;analyse.disabled=!files.length;uploadBtn.disabled=true;chosen=[];preview.innerHTML='';setStatus(files.length+' photographs ready for analysis. Originals have not been uploaded.');});
function hamming(a,b){let n=0;for(let i=0;i<Math.min(a.length,b.length);i++)if(a[i]!==b[i])n++;return n+Math.abs(a.length-b.length)}
async function inspect(file){
 const bmp=await createImageBitmap(file,{resizeWidth:320,resizeHeight:220,resizeQuality:'low'});const c=document.createElement('canvas');c.width=64;c.height=48;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bmp,0,0,c.width,c.height);bmp.close();const d=x.getImageData(0,0,c.width,c.height).data;let sum=0,edges=0;const gray=new Uint8Array(c.width*c.height);for(let i=0,j=0;i<d.length;i+=4,j++){const g=(d[i]*.299+d[i+1]*.587+d[i+2]*.114)|0;gray[j]=g;sum+=g}const avg=sum/gray.length;let hash='';for(let yy=0;yy<8;yy++)for(let xx=0;xx<8;xx++){const sx=Math.floor(xx*c.width/8),sy=Math.floor(yy*c.height/8);hash+=gray[sy*c.width+sx]>=avg?'1':'0'}for(let y=1;y<c.height;y++)for(let xx=1;xx<c.width;xx++){const i=y*c.width+xx;edges+=Math.abs(gray[i]-gray[i-1])+Math.abs(gray[i]-gray[i-c.width])}return{file,hash,quality:Math.round(edges/(c.width*c.height))};
}
function burstGroups(sorted){const groups=[];let g=[];for(const f of sorted){if(!g.length||Math.abs(f.lastModified-g[g.length-1].lastModified)<=1800)g.push(f);else{groups.push(g);g=[f]}}if(g.length)groups.push(g);return groups}
analyse.addEventListener('click',async()=>{
 analyse.disabled=true;uploadBtn.disabled=true;chosen=[];preview.innerHTML='';const sorted=[...files].sort((a,b)=>a.lastModified-b.lastModified);const groups=burstGroups(sorted);document.getElementById('bursts').textContent=groups.length;let done=0;
 for(let gi=0;gi<groups.length;gi++){const inspected=[];for(const f of groups[gi]){try{inspected.push(await inspect(f))}catch{}done++;setBar(done,files.length);setStatus('Analysing '+done+' of '+files.length+'…')}inspected.sort((a,b)=>b.quality-a.quality||b.file.size-a.file.size);const keep=[];for(const item of inspected){if(!keep.some(k=>hamming(k.hash,item.hash)<=7)){keep.push(item)}if(keep.length>=2)break}for(const k of keep)chosen.push({...k,burstId:'b'+String(gi+1).padStart(5,'0')});}
 document.getElementById('selected').textContent=chosen.length;document.getElementById('saved').textContent=Math.max(0,files.length-chosen.length);setStatus('Analysis complete. '+chosen.length+' strong frames selected from '+files.length+' photographs.');setBar(1,1);uploadBtn.disabled=!chosen.length;analyse.disabled=false;await drawPreviews();
});
async function watermarkedBlob(file,maxSide=2400){const bmp=await createImageBitmap(file);let w=bmp.width,h=bmp.height;const scale=Math.min(1,maxSide/Math.max(w,h));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(bmp,0,0,w,h);bmp.close();const font=Math.max(24,Math.round(w*.026));const pad=Math.round(font*.7);x.font='600 '+font+'px Arial';const label='✈  MikeAircraft  ©';const tw=x.measureText(label).width;const bx=w-tw-pad*2,by=h-font-pad*2; x.fillStyle='rgba(0,0,0,.28)';x.beginPath();x.roundRect(bx,by,tw+pad*2,font+pad*1.5,font*.35);x.fill();x.textBaseline='middle';x.shadowColor='rgba(255,255,255,.55)';x.shadowBlur=1;x.shadowOffsetX=1;x.shadowOffsetY=1;x.fillStyle='rgba(5,12,18,.62)';x.fillText(label,bx+pad,by+(font+pad*1.5)/2);x.shadowColor='rgba(0,0,0,.85)';x.shadowOffsetX=-1;x.shadowOffsetY=-1;x.fillStyle='rgba(255,255,255,.48)';x.fillText(label,bx+pad,by+(font+pad*1.5)/2);return await new Promise(r=>c.toBlob(r,'image/jpeg',.88));}
async function drawPreviews(){preview.innerHTML='';for(const item of chosen.slice(0,30)){const b=await watermarkedBlob(item.file,900);const u=URL.createObjectURL(b);const div=document.createElement('div');div.className='thumb';const img=document.createElement('img');img.src=u;img.onload=()=>URL.revokeObjectURL(u);const meta=document.createElement('div');meta.className='meta';meta.textContent=item.file.name+' • quality '+item.quality+' • '+item.burstId;div.append(img,meta);preview.append(div)}}
function safeName(n){return n.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'_').slice(0,80)}
uploadBtn.addEventListener('click',async()=>{uploadBtn.disabled=true;analyse.disabled=true;const airport=document.getElementById('airport').value;let ok=0;for(let i=0;i<chosen.length;i++){const item=chosen[i];try{setStatus('Watermarking and uploading '+(i+1)+' of '+chosen.length+'…');setBar(i,chosen.length);const blob=await watermarkedBlob(item.file);const stamp=new Date(item.file.lastModified||Date.now()).toISOString().replace(/[:.]/g,'-');const pathname='photo-library/'+airport+'/'+stamp+'_'+safeName(item.file.name)+'.jpg';await upload(pathname,blob,{access:'public',handleUploadUrl:'/api/photo-upload',clientPayload:JSON.stringify({sourceName:item.file.name,sourceModified:item.file.lastModified,burstId:item.burstId,qualityScore:item.quality,airport})});ok++;}catch(e){console.error(e);setStatus('Upload stopped: '+(e?.message||e));break}}setBar(ok,chosen.length);setStatus(ok===chosen.length?'Finished: '+ok+' watermarked photos added to the MikeAircraft library.':'Uploaded '+ok+' of '+chosen.length+'.');uploadBtn.disabled=false;analyse.disabled=false;});
</script></body></html>`;
  return res.status(200).send(html);
};
